name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Test
        run: dotnet test --configuration Release
        env:
          # Опционально: переключить профиль конфига
          ASPNETCORE_ENVIRONMENT: Test

  compose:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
    env:
      JWT_KEY: ${{ secrets.JWT_SECRET_KEY }}
      ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
      POSTGRES_USER: ${{secrets.vbifsus123}}
      POSTGRES_PASSWORD: ${{secrets.vbifsus123}}
